### ISSUE TITLE
Frontend setup

### ISSUE THREAD

**Issue by elainelin313** [HaikDivanyan/GraphicalResourceForEnrollmentGuidance#15]
## User Story
As a student, I need a page to upload my DARS. 

## Detailed Description
Users should see a landing page that shows instructions and how to get started.

## Tasks
- [x] Set up react page for frontend
- [x] Create UI mockup with Figma
- [x] Create landing page with nav bar + Upload/Get started buttons
- [x] Set up upload and get started buttons (routing)
- [x] Create upload section with the upload function

**Comment by mop03** [comment]
Figma Mockup: https://www.figma.com/file/rPpbqeqQGPS8mA8Y86I3tx/GREG?type=design&node-id=33-1023&mode=design&t=KSHQ29JQZUIqZTxF-0
