### ISSUE TITLE
Class data from DARS uploading

### ISSUE THREAD

**Issue by edanchu** [HaikDivanyan/GraphicalResourceForEnrollmentGuidance#2]
## User Story
As a student I would like to upload my DARS to the app so that I can see which classes I need are offered this quarter.

## Detailed Description
Students should be able to upload their DARS and get a list of relevant classes offered by UCLA for the upcoming quarter along with details about those classes.

## Acceptance Criteria
- [ ] Given An uploaded DARS, then a list of available relevant classes should be output along with requirements and sub requirements

## Tasks
- [x] Parse DARS for requirements and subrequirements
- [x] Extract class text
- [x] Parse class text to major and class number
- [x] Deal with ranges
- [x] Create matching between subject area names and true subject areas.
