### ISSUE TITLE
Bruinwalk Data

### ISSUE THREAD

**Issue by edanchu** [HaikDivanyan/GraphicalResourceForEnrollmentGuidance#23]
## User Story
As a user, I would like to see class ratings so that I can make informed decisions.

## Acceptance Criteria
- [x] Given a class is requested, then bruinwalk rating is present in our data

## Tasks
- [x] map class name to bw page
- [x] scrape bw page
- [x] parse page for rating
- [x] create cache for controller
