### ISSUE TITLE
registrar data

### ISSUE THREAD

**Issue by edanchu** [HaikDivanyan/GraphicalResourceForEnrollmentGuidance#24]
## User Story
As astudent, I would like to see current registrar data for a class so that i can be informed.

## Acceptance Criteria
- [x] Given a class is offered this quarter, then the class data is available

## Tasks
- [x] create parser using selenium
- [x] create cache
- [x] create backend data structures
- [x] scrape all 185 majors
- [x] deal with odd class formats
