### ISSUE TITLE
data controller

### ISSUE THREAD

**Issue by edanchu** [HaikDivanyan/GraphicalResourceForEnrollmentGuidance#25]
## User Story
As a dev, I would like a data controller for the scraping so that I can quickly and easily get parsed dars data.

## Acceptance Criteria
- [ ] Given a dars is uploaded, then correct class and requirement data is returned
- [ ] given data is already aquired, cache is used to retrieve it instead of scraping and parsing anew

# Tasks
- [x] create partial objects
- [x] integrate dars parser
- [x] integrate registrar scraper
- [x] integrate bw controller
- [ ] integrate hotseat controller
- [ ] integrate grade distributions
