### ISSUE TITLE
Class fill up speed data

### ISSUE THREAD

**Issue by edanchu** [HaikDivanyan/GraphicalResourceForEnrollmentGuidance#5]
## User Story
As a student I would like to view historical data on how fast a class fills up so I know what classes to prioritize enrolling for during each enrollment pass.

## Detailed Description
Using hotseat.io show data on how quickly a class fills up during enrollment in previous quarters.

## Acceptance Criteria
- [x] Given hotseat.io has data about that class, then show the enrollment/time graph
- [x] Given hotseat.io doesn't have data about the class, then don't show any data

## Tasks
- [x] Create selenium scraper for js data
- [x] parse scraped data
- [x] map between class name and professor to correct window
