### ISSUE TITLE
Professor reviews

### ISSUE THREAD

**Issue by edanchu** [HaikDivanyan/GraphicalResourceForEnrollmentGuidance#6]
## User Story
As a student I would like to view reviews of class professors so that I can make sure to take one that matches my learning style.

## Detailed Description
Use bruinwalk to source reviews of professors and classes.

## Acceptance Criteria
- [x] Given a professor's data is found on bruinwalk display the data
- [x] Given a professor's data is not found bruinwalk, then display no data

## Tasks
- [x] Create mapping function from professor name to bruinwalk page
- [x] Create parser to extract bruinwalk textual data
- [x] format retrieved textual data
